### ISSUE TITLE
NoMethodError: undefined method `can_be_synced?' for nil:NilClass

### ISSUE THREAD

**Issue by mbajur** [mbajur/hcpl#40]
https://sentry.io/nemuco/rails/issues/420882538/

```
NoMethodError: undefined method `can_be_synced?' for nil:NilClass
  app/controllers/posts_controller.rb:95:in `resync_post_event_data'
    return false unless @post.event.can_be_synced?
  app/controllers/posts_controller.rb:48:in `show'
    resync_post_event_data
...
(62 additional frame(s) were not displayed)

NoMethodError: undefined method `can_be_synced?' for nil:NilClass
```

**Comment by mbajur** [comment]
It seems event was not created for this link: https://www.facebook.com/events/603952403269138
